#!/usr/bin/env python3
"""
nn_LORO.py
==========
Leave-One-Rock-Out (LORO) cross-validation for burial depth estimation
using paired directional vibration features and a Multilayer Perceptron.

This is the main evaluation script for the paper:
  "Burial Depth Estimation for Partially Embedded Rocks Using
   Scanning Laser Doppler Vibrometry and Neural Networks"

Fixed-configuration ablation at the paper's matched reference
(16, 8, 4)/tanh/alpha=5 with the mean/difference encoding (Table II):
48.4 (baseline) / 24.4 (+zeta) / 37.6 (+beta) / 22.6 (+zeta+beta) % MAPE.
For the headline (absolute) estimate use nested_cv.py instead.

Usage
-----
  # Run the paper's proposed eleven-feature set (default):
  python nn_LORO.py

  # Run a specific ablation rung:
  python nn_LORO.py --variant baseline
  python nn_LORO.py --variant +zeta
  python nn_LORO.py --variant +beta
  python nn_LORO.py --variant +zeta+beta   # (default, proposed feature set)
  python nn_LORO.py --variant all

  # Custom hyperparameters:
  python nn_LORO.py --alpha 5.0 --hidden-layers 16 8 4 --seed 0

  # Skip plot generation:
  python nn_LORO.py --no-plot

Requires
--------
  training_dataset.csv  (generated by make_training_dataset.py)
"""

import argparse
import sys
import numpy as np
import pandas as pd
from joblib import Parallel, delayed
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from pathlib import Path
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))  # repo root
from paired_dataset import load_paired, TARGET

# ============================================================================
# Feature set definitions (mean/difference encoding, paper Table II)
# ============================================================================
FEAT_BASELINE = ["w_mean", "fn_mean", "Mp_mean", "he",
                 "w_diff", "fn_diff", "Mp_diff"]

FEAT_ZETA = FEAT_BASELINE + ["zeta_mean", "zeta_diff"]

FEAT_BETA = FEAT_BASELINE + ["beta_mean", "beta_diff"]

FEAT_ZETA_BETA = FEAT_BASELINE + ["zeta_mean", "zeta_diff",
                                  "beta_mean", "beta_diff"]   # proposed model

VARIANTS = {
    "baseline":    FEAT_BASELINE,
    "+zeta":       FEAT_ZETA,
    "+beta":       FEAT_BETA,
    "+zeta+beta":  FEAT_ZETA_BETA,
}


# ============================================================================
# Model factory
# ============================================================================
def make_model(hidden_layers, activation, alpha, seed, lr, max_iter,
               n_iter_no_change, tol):
    return Pipeline([
        ("scaler", StandardScaler()),
        ("mlp", MLPRegressor(
            hidden_layer_sizes=hidden_layers,
            activation=activation,
            max_iter=max_iter,
            random_state=seed,
            alpha=alpha,
            learning_rate_init=lr,
            n_iter_no_change=n_iter_no_change,
            tol=tol,
        )),
    ])


# ============================================================================
# LORO cross-validation
# ============================================================================
def run_loro(df, features, model_kwargs):
    """Run strict Leave-One-Rock-Out CV."""
    loo_rows = []
    for rock_out in df["rock"].unique():
        train = df[df["rock"] != rock_out]
        test = df[df["rock"] == rock_out]
        model = make_model(**model_kwargs)
        model.fit(train[features].values, train[TARGET].values)
        y_pred = model.predict(test[features].values)
        for i, (_, row) in enumerate(test.iterrows()):
            loo_rows.append(dict(
                rock=row["rock"], pct=row["pct"], date=row["date"],
                h_true=row["h_cm"], h_pred=y_pred[i],
                area_cm2=row["area_cm2"],
                he_cm=row["he_cm"], M_kg=row["M_kg"], density=row["density"],
            ))

    lr = pd.DataFrame(loo_rows)
    # orientation-aware horizontal cross-sectional area (w_b * w_s)
    lr["V_true_cm3"] = lr["area_cm2"] * (lr["he_cm"] + lr["h_true"])
    lr["V_pred_cm3"] = lr["area_cm2"] * (lr["he_cm"] + lr["h_pred"])
    lr["h_err_pct"] = (lr["h_pred"] - lr["h_true"]) / lr["h_true"] * 100
    lr["V_err_pct"] = (lr["V_pred_cm3"] - lr["V_true_cm3"]) / lr["V_true_cm3"] * 100
    return lr


def compute_metrics(lr):
    h_mape = lr["h_err_pct"].abs().mean()
    h_rmse = np.sqrt(np.mean((lr["h_pred"] - lr["h_true"]) ** 2))
    V_mape = lr["V_err_pct"].abs().mean()
    V_rmse = np.sqrt(np.mean((lr["V_pred_cm3"] - lr["V_true_cm3"]) ** 2))
    return h_mape, h_rmse, V_mape, V_rmse


# ============================================================================
# Permutation importance
# ============================================================================
def permutation_importance(df, features, model_kwargs, n_repeats=20,
                           seeds=range(20)):
    """Train on the full dataset (one model per seed), shuffle each feature,
    and average the RMSE increase over shuffles and seeds (paper Sec. VII-C)."""
    X = df[features].values
    y = df[TARGET].values
    rng = np.random.default_rng(0)
    deltas = {f: [] for f in features}
    base_rmses = []
    for seed in seeds:
        kw = dict(model_kwargs, seed=seed)
        model = make_model(**kw)
        model.fit(X, y)
        base = np.sqrt(np.mean((model.predict(X) - y) ** 2))
        base_rmses.append(base)
        for fi, fname in enumerate(features):
            for _ in range(n_repeats):
                Xs = X.copy()
                rng.shuffle(Xs[:, fi])
                rmse_s = np.sqrt(np.mean((model.predict(Xs) - y) ** 2))
                deltas[fname].append(rmse_s - base)
    importance = {f: float(np.mean(v)) for f, v in deltas.items()}
    return importance, float(np.mean(base_rmses))


# ============================================================================
# Figure generation (paper Fig. 5)
# ============================================================================
def make_panel(ax, x_true, y_pred, xlabel, ylabel):
    data_max = max(x_true.max(), y_pred.max())
    raw_step = data_max / 5.0
    mag = 10 ** np.floor(np.log10(raw_step))
    tick_step = float(mag * min([1, 2, 5, 10],
                                key=lambda f: abs(f * mag - raw_step)))
    lim_hi = float(np.ceil(data_max / (tick_step / 2)) * (tick_step / 2))
    xs = np.array([0.0, lim_hi])

    ax.plot(xs, xs * 1.25, ':', color='#cc3333', linewidth=0.9, label=r'$\pm$25%')
    ax.plot(xs, xs * 0.75, ':', color='#cc3333', linewidth=0.9)
    ax.plot(xs, xs, 'r--', linewidth=1.2, label='Perfect')
    ax.scatter(x_true, y_pred,
               s=30, alpha=0.65, edgecolors='#1c4f8a', linewidths=0.5,
               color='#3a7ebf', zorder=3)

    ax.set_xlabel(xlabel, fontsize=7)
    ax.set_ylabel(ylabel, fontsize=7)
    ax.set_xlim(0.0, lim_hi)
    ax.set_ylim(0.0, lim_hi)
    ax.set_aspect('equal', adjustable='box')
    ax.xaxis.set_major_locator(ticker.MultipleLocator(tick_step))
    ax.yaxis.set_major_locator(ticker.MultipleLocator(tick_step))
    ax.tick_params(labelsize=6.5)
    ax.legend(fontsize=6.5, loc='upper left')


def save_figure(lr, output_dir):
    """Generate the two-panel pred-vs-true figure (paper Fig. 5)."""
    h_true = lr["h_true"].values
    h_pred = lr["h_pred"].values
    V_true = lr["V_true_cm3"].values
    V_pred = lr["V_pred_cm3"].values

    # Individual panels
    for data_x, data_y, xl, yl, fname in [
        (h_true, h_pred,
         'True $h$ (cm)', 'Predicted $h$ (cm)',
         'paper_results_h.png'),
        (V_true, V_pred,
         r'True $V$ (cm$^3$)', r'Predicted $V$ (cm$^3$)',
         'paper_results_V.png'),
    ]:
        fig_s, ax_s = plt.subplots(1, 1, figsize=(3.4, 3.4))
        make_panel(ax_s, data_x, data_y, xl, yl)
        out_path = output_dir / fname
        fig_s.savefig(out_path, dpi=300, bbox_inches='tight')
        plt.close(fig_s)
        print(f"  Saved -> {out_path}")

    # Combined two-panel
    fig, axes = plt.subplots(1, 2, figsize=(7.0, 3.5))
    fig.subplots_adjust(wspace=0.38)
    make_panel(axes[0], h_true, h_pred,
               'True $h$ (cm)', 'Predicted $h$ (cm)')
    make_panel(axes[1], V_true, V_pred,
               r'True $V$ (cm$^3$)', r'Predicted $V$ (cm$^3$)')
    out_path = output_dir / "paper_results.png"
    fig.savefig(out_path, dpi=300, bbox_inches='tight')
    plt.close(fig)
    print(f"  Saved -> {out_path}")


# ============================================================================
# CLI
# ============================================================================
def parse_args():
    p = argparse.ArgumentParser(
        description="LORO cross-validation for burial depth estimation.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument("--variant", default="+zeta+beta",
                   choices=list(VARIANTS.keys()) + ["all"],
                   help="Feature set variant (default: +zeta+beta, the proposed set)")
    p.add_argument("--csv", default=None,
                   help="Path to training_dataset.csv (default: training_dataset.csv at the repo root)")
    p.add_argument("--output-dir", default=None,
                   help="Output directory for results CSV and figures (default: repo-root output/)")
    p.add_argument("--alpha", type=float, default=5.0,
                   help="L2 regularization (default: 5.0)")
    p.add_argument("--hidden-layers", type=int, nargs="+", default=[16, 8, 4],
                   help="Hidden layer sizes (default: 16 8 4)")
    p.add_argument("--seed", type=int, default=0,
                   help="Seed for the detailed CSV/figures/permutation (default: 0)")
    p.add_argument("--seeds", type=int, default=20,
                   help="Number of seeds for the mean +/- std summary "
                        "(Table II; default: 20; set 1 for a quick run)")
    p.add_argument("--no-plot", action="store_true",
                   help="Skip figure generation")
    return p.parse_args()


def main():
    args = parse_args()
    base = Path(__file__).resolve().parents[1]  # repo root

    csv_path = Path(args.csv) if args.csv else base / "training_dataset.csv"
    output_dir = Path(args.output_dir) if args.output_dir else base / "output"
    output_dir.mkdir(exist_ok=True)

    if not csv_path.exists():
        print(f"ERROR: {csv_path} not found.")
        print("Run make_training_dataset.py first to generate it.")
        sys.exit(1)

    model_kwargs = dict(
        hidden_layers=tuple(args.hidden_layers),
        activation="tanh",
        alpha=args.alpha,
        seed=args.seed,
        lr=5e-4,
        max_iter=50_000,
        n_iter_no_change=300,
        tol=1e-6,
    )

    # ── Load data ───────────────────────────────────────────────────────────
    print("Loading paired dataset ...", flush=True)
    df = load_paired(csv_path)
    print(f"  {len(df)} paired samples, {df['rock'].nunique()} rocks\n")

    # ── Select variants to run ──────────────────────────────────────────────
    if args.variant == "all":
        run_variants = list(VARIANTS.items())
    else:
        run_variants = [(args.variant, VARIANTS[args.variant])]

    # ── Run LORO (all seeds in parallel per variant) ────────────────────────
    results = {}
    for name, feat in run_variants:
        print(f"Running LORO: {name} ({len(feat)} inputs, "
              f"{args.seeds} seed(s)) ...", flush=True)
        lrs = Parallel(n_jobs=-1)(
            delayed(run_loro)(df, feat, dict(model_kwargs, seed=s))
            for s in range(args.seeds))
        per = np.array([compute_metrics(lr) for lr in lrs])
        detail = lrs[args.seed] if args.seed < args.seeds else \
            run_loro(df, feat, dict(model_kwargs, seed=args.seed))
        results[name] = (detail, feat, per)

    # ── Summary table (mean +/- std over seeds; paper Table II) ────────────
    print()
    print("=" * 70)
    print(f"LORO Cross-Validation Summary ({args.seeds} seeds)")
    print("=" * 70)
    print(f"  Architecture : {args.hidden_layers}  tanh  alpha={args.alpha}")
    print()
    print(f"  {'Variant':<16} {'Inputs':>6} {'h MAPE (%)':>14} "
          f"{'h RMSE (cm)':>14} {'V MAPE (%)':>13}")
    print("-" * 70)

    best_name = min(results, key=lambda n: results[n][2][:, 0].mean())
    for name, (lr, feat, per) in results.items():
        flag = "  <-- BEST" if name == best_name and len(results) > 1 else ""
        print(f"  {name:<16} {len(feat):6d} "
              f"{per[:, 0].mean():6.1f} +/- {per[:, 0].std():3.1f} "
              f"{per[:, 1].mean():6.3f} +/- {per[:, 1].std():5.3f} "
              f"{per[:, 2].mean():5.1f} +/- {per[:, 2].std():3.1f}{flag}")

    # ── Save results CSV ────────────────────────────────────────────────────
    print()
    for name, (lr, feat, per) in results.items():
        tag = name.replace("+", "").replace(" ", "_")
        out_csv = output_dir / f"loro_results_{tag}.csv"
        lr.sort_values(["rock", "pct", "date"]).to_csv(out_csv, index=False)
        print(f"  Saved -> {out_csv}")

    # ── Permutation importance (for the best / selected variant) ────────────
    print()
    print("=" * 70)
    print("Permutation Feature Importance (trained on full data)")
    print("=" * 70)
    for name, (lr, feat, per) in results.items():
        importance, base_rmse = permutation_importance(df, feat, model_kwargs)
        print(f"\n  {name} (base RMSE = {base_rmse:.3f} cm):")
        ranked = sorted(importance.items(), key=lambda x: -x[1])
        for rank, (fname, delta) in enumerate(ranked, 1):
            pct = delta / base_rmse * 100
            bar = "#" * max(0, int(delta / 0.05))
            print(f"    {rank:2d}. {fname:14s}  dRMSE = {delta:+.3f} cm  "
                  f"({pct:+.0f}%)  {bar}")

    # ── Generate figure ─────────────────────────────────────────────────────
    if not args.no_plot:
        print()
        # Use the proposed model if available, otherwise the first result
        plot_name = "+zeta+beta" if "+zeta+beta" in results else list(results.keys())[0]
        plot_lr = results[plot_name][0]
        hm, hr, Vm, Vr = compute_metrics(plot_lr)
        print(f"Generating figures for '{plot_name}':")
        print(f"  h: MAPE={hm:.1f}%  RMSE={hr:.2f} cm")
        print(f"  V: MAPE={Vm:.1f}%  RMSE={Vr:.1f} cm3")
        save_figure(plot_lr, output_dir)

    print("\nDone.")


if __name__ == "__main__":
    main()
